/public-chatbots:
  get:
    operationId: getSinglePublicChatbotConfig
    summary: Get public configuration for a chatbot
    description: >-
      Retrieves the public configuration for a specific chatbot (which is a Flowise chatflow).
      This includes UI settings from the chatflow's `chatbotConfig`, file upload capabilities,
      and the raw `flowData`. This endpoint is used by the embedded chatbot UI.
    tags:
      - Public Chatbots
    parameters:
      - name: id
        in: path
        description: The ID of the chatflow to retrieve public config for
        required: true
        schema:
          type: string
          format: uuid
    responses:
      '200':
        description: >-
          Successfully retrieved the public chatbot configuration.
          Returns either a configuration object or the string "OK" if no specific configuration is found.
        content:
          application/json:
            schema:
              $ref: '../../schemas/modules/PublicChatbotsSchemas.yaml#/components/schemas/PublicChatbotConfigResponse'
      '404':
        description: Chatflow with the specified ID not found
        content:
          application/json:
            schema:
              $ref: '../../schemas/shared/CommonSchemas.yaml#/components/schemas/ErrorResponse'
      '412':
        description: ID parameter not provided
        content:
          application/json:
            schema:
              $ref: '../../schemas/shared/CommonSchemas.yaml#/components/schemas/ErrorResponse'
      '500':
        description: Error parsing chatbotConfig or other server-side issue
        content:
          application/json:
            schema:
              $ref: '../../schemas/shared/CommonSchemas.yaml#/components/schemas/ErrorResponse' 