# global:
#   scrape_interval: 5s
# scrape_configs:
#   - job_name: "Remodl AI Platform"
#     static_configs:
#       - targets: ["localhost:8080","localhost:3000"]

#     metrics_path: /api/v1/metrics/
#     scheme: http

global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "Remodl AI Platform"
    static_configs:
      - targets: ["localhost:8080", "localhost:3000"]
    metrics_path: /api/v1/metrics/
    scheme: http
    tls_config:
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "host.docker.internal:(.*)"
        replacement: "localhost:$1"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]