openapi: 3.1.0
info:
  title: Shared Common Schemas
  version: '1.0'
components:
  schemas:
    ChatMessage:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          enum: [userMessage, apiMessage, user, assistant, system, function, tool]
          description: The role of the message sender.
        content:
          type: string
          description: The textual content of the message.
        name:
          type: string
          description: The name of the tool that was called (if role is 'tool').
          nullable: true
        tool_call_id:
          type: string
          description: The ID of the tool call (if role is 'tool').
          nullable: true
        tool_calls:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              type:
                type: string
                enum: [function]
              function:
                type: object
                properties:
                  name:
                    type: string
                  arguments:
                    type: string # JSON string
          nullable: true

    ErrorResponse:
      type: object
      required:
        - statusCode
        # - error # Error can be missing if thrown directly as new Error(message)
        - message
      properties:
        statusCode:
          type: integer
          format: int32
          description: HTTP status code.
        error:
          type: string
          description: Short error description (e.g., 'Not Found', 'Internal ServerError').
          nullable: true
        message:
          type: string
          description: Detailed error message.
        requestId: # Optional
          type: string
          description: Optional request identifier for tracing.
          nullable: true
        stack: # Often present in non-production from global error handler
            type: string
            description: "Stack trace (typically available in development mode only)."
            nullable: true
            
    DeleteResultSchema:
      type: object
      description: "Standard TypeORM DeleteResult object."
      properties:
        raw:
          type: array
          items: {}
          description: "Raw results returned by the database driver."
        affected:
          type: integer
          nullable: true
          description: "Number of rows affected by the delete operation."
