import { ChatFlow } from './ChatFlow';
import { ChatMessage } from './ChatMessage';
import { ChatMessageFeedback } from './ChatMessageFeedback';
import { Credential } from './Credential';
import { Tool } from './Tool';
import { Assistant } from './Assistant';
import { Variable } from './Variable';
import { DocumentStore } from './DocumentStore';
import { DocumentStoreFileChunk } from './DocumentStoreFileChunk';
import { Lead } from './Lead';
import { UpsertHistory } from './UpsertHistory';
import { ApiKey } from './ApiKey';
import { CustomTemplate } from './CustomTemplate';
export declare const entities: {
    ChatFlow: typeof ChatFlow;
    ChatMessage: typeof ChatMessage;
    ChatMessageFeedback: typeof ChatMessageFeedback;
    Credential: typeof Credential;
    Tool: typeof Tool;
    Assistant: typeof Assistant;
    Variable: typeof Variable;
    DocumentStore: typeof DocumentStore;
    DocumentStoreFileChunk: typeof DocumentStoreFileChunk;
    Lead: typeof Lead;
    UpsertHistory: typeof UpsertHistory;
    ApiKey: typeof ApiKey;
    CustomTemplate: typeof CustomTemplate;
};
