openapi: 3.1.0
info:
  title: Prompts Lists Module Schemas
  version: '1.0'
components:
  schemas:
    PromptsListRequestBody:
      type: object
      properties:
        tags:
          type: string
          description: Optional comma-separated tags to filter prompts from Langchain Hub.
          example: "agent,react"

    LangchainHubRepo:
      # This schema represents the structure of an object within the 'repos' array
      # returned by the Langchain Hub API. Structure is based on observed responses
      # and may need refinement if the Hub API changes.
      type: object
      properties:
        id:
          type: integer
        author:
          type: string
        full_name:
          type: string
        description:
          type: string
          nullable: true
        num_likes:
          type: integer
        is_public:
          type: boolean
        is_pinned:
          type: boolean
        last_updated:
          type: string
          format: date-time
        commit_hash:
          type: string
          nullable: true
        tags:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              slug:
                type: string
      # Add other potential fields if known
      additionalProperties: true

    PromptsListSuccessResponse:
      type: object
      required:
        - status
        - repos
      properties:
        status:
          type: string
          enum: [OK]
        repos:
          type: array
          description: Array of prompt repositories fetched from Langchain Hub.
          items:
            $ref: '#/components/schemas/LangchainHubRepo'

    PromptsListServiceErrorResponse: # Specific error structure returned by the service on fetch failure
      type: object
      required:
        - status
        - repos
      properties:
        status:
          type: string
          enum: [ERROR]
        repos:
          type: array
          description: Always an empty array on service error.
          items:
            type: object # Empty array means items schema doesn't strictly matter
          maxItems: 0
