/*
* This file is automatically generated by Supabase.
* Do not edit this file manually.
* instead, run supabase gen types typescript --project-id voksjtjrshonjadwjozt > datase.types.ts
*/

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      application_api_keys: {
        Row: {
          api_key: string
          application_id: string
          created_at: string
          created_by: string
          expires_at: string | null
          hashed_key: string
          id: string
          is_active: boolean | null
          key_name: string
          last_used_at: string | null
          organization_id: string | null
          read_permission: boolean | null
          updated_at: string
          write_permission: boolean | null
        }
        Insert: {
          api_key: string
          application_id: string
          created_at?: string
          created_by: string
          expires_at?: string | null
          hashed_key: string
          id?: string
          is_active?: boolean | null
          key_name: string
          last_used_at?: string | null
          organization_id?: string | null
          read_permission?: boolean | null
          updated_at?: string
          write_permission?: boolean | null
        }
        Update: {
          api_key?: string
          application_id?: string
          created_at?: string
          created_by?: string
          expires_at?: string | null
          hashed_key?: string
          id?: string
          is_active?: boolean | null
          key_name?: string
          last_used_at?: string | null
          organization_id?: string | null
          read_permission?: boolean | null
          updated_at?: string
          write_permission?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: "application_api_keys_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "application_api_keys_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      application_billing_plans: {
        Row: {
          application_id: string
          created_at: string
          description: string | null
          feature_advanced_analytics: boolean | null
          feature_api_access: boolean | null
          feature_custom_domain: boolean | null
          feature_priority_support: boolean | null
          feature_unlimited_users: boolean | null
          id: string
          interval: string | null
          is_default: boolean | null
          name: string
          price: number | null
          updated_at: string
        }
        Insert: {
          application_id: string
          created_at?: string
          description?: string | null
          feature_advanced_analytics?: boolean | null
          feature_api_access?: boolean | null
          feature_custom_domain?: boolean | null
          feature_priority_support?: boolean | null
          feature_unlimited_users?: boolean | null
          id?: string
          interval?: string | null
          is_default?: boolean | null
          name: string
          price?: number | null
          updated_at?: string
        }
        Update: {
          application_id?: string
          created_at?: string
          description?: string | null
          feature_advanced_analytics?: boolean | null
          feature_api_access?: boolean | null
          feature_custom_domain?: boolean | null
          feature_priority_support?: boolean | null
          feature_unlimited_users?: boolean | null
          id?: string
          interval?: string | null
          is_default?: boolean | null
          name?: string
          price?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "application_billing_plans_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      application_chatflows: {
        Row: {
          application_id: string
          chatflow_id: string
          created_at: string
          folder_path: string | null
          id: string
          updated_at: string
        }
        Insert: {
          application_id: string
          chatflow_id: string
          created_at?: string
          folder_path?: string | null
          id?: string
          updated_at?: string
        }
        Update: {
          application_id?: string
          chatflow_id?: string
          created_at?: string
          folder_path?: string | null
          id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "application_chatflows_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      application_credentials: {
        Row: {
          application_id: string
          created_at: string
          credential_id: string
          id: string
          updated_at: string
        }
        Insert: {
          application_id: string
          created_at?: string
          credential_id: string
          id?: string
          updated_at?: string
        }
        Update: {
          application_id?: string
          created_at?: string
          credential_id?: string
          id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "application_credentials_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      application_folders: {
        Row: {
          application_id: string
          created_at: string
          id: string
          name: string
          parent_folder_id: string | null
          path: string
          updated_at: string
        }
        Insert: {
          application_id: string
          created_at?: string
          id?: string
          name: string
          parent_folder_id?: string | null
          path: string
          updated_at?: string
        }
        Update: {
          application_id?: string
          created_at?: string
          id?: string
          name?: string
          parent_folder_id?: string | null
          path?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "application_folders_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "application_folders_parent_folder_id_fkey"
            columns: ["parent_folder_id"]
            isOneToOne: false
            referencedRelation: "application_folders"
            referencedColumns: ["id"]
          },
        ]
      }
      application_settings: {
        Row: {
          advanced_analytics_enabled: boolean | null
          api_access_enabled: boolean | null
          api_calls_daily_limit: number | null
          api_calls_monthly_limit: number | null
          application_id: string
          created_at: string
          custom_domains_enabled: boolean | null
          enabled_models: string[] | null
          file_uploads_enabled: boolean | null
          sso_enabled: boolean | null
          storage_max_gb: number | null
          updated_at: string
          users_max_count: number | null
        }
        Insert: {
          advanced_analytics_enabled?: boolean | null
          api_access_enabled?: boolean | null
          api_calls_daily_limit?: number | null
          api_calls_monthly_limit?: number | null
          application_id: string
          created_at?: string
          custom_domains_enabled?: boolean | null
          enabled_models?: string[] | null
          file_uploads_enabled?: boolean | null
          sso_enabled?: boolean | null
          storage_max_gb?: number | null
          updated_at?: string
          users_max_count?: number | null
        }
        Update: {
          advanced_analytics_enabled?: boolean | null
          api_access_enabled?: boolean | null
          api_calls_daily_limit?: number | null
          api_calls_monthly_limit?: number | null
          application_id?: string
          created_at?: string
          custom_domains_enabled?: boolean | null
          enabled_models?: string[] | null
          file_uploads_enabled?: boolean | null
          sso_enabled?: boolean | null
          storage_max_gb?: number | null
          updated_at?: string
          users_max_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "application_settings_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: true
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      application_stats: {
        Row: {
          api_calls_count: number | null
          application_id: string
          created_at: string
          credential_count: number | null
          database_count: number | null
          file_count: number | null
          flow_count: number | null
          growth_percentage: number | null
          image_count: number | null
          last_updated: string
          organization_count: number | null
          revenue_amount: number | null
          run_count: number | null
          storage_used_bytes: number | null
          updated_at: string
          user_count: number | null
        }
        Insert: {
          api_calls_count?: number | null
          application_id: string
          created_at?: string
          credential_count?: number | null
          database_count?: number | null
          file_count?: number | null
          flow_count?: number | null
          growth_percentage?: number | null
          image_count?: number | null
          last_updated?: string
          organization_count?: number | null
          revenue_amount?: number | null
          run_count?: number | null
          storage_used_bytes?: number | null
          updated_at?: string
          user_count?: number | null
        }
        Update: {
          api_calls_count?: number | null
          application_id?: string
          created_at?: string
          credential_count?: number | null
          database_count?: number | null
          file_count?: number | null
          flow_count?: number | null
          growth_percentage?: number | null
          image_count?: number | null
          last_updated?: string
          organization_count?: number | null
          revenue_amount?: number | null
          run_count?: number | null
          storage_used_bytes?: number | null
          updated_at?: string
          user_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "application_stats_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: true
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      application_tools: {
        Row: {
          application_id: string
          created_at: string
          id: string
          tool_id: string
          updated_at: string
        }
        Insert: {
          application_id: string
          created_at?: string
          id?: string
          tool_id: string
          updated_at?: string
        }
        Update: {
          application_id?: string
          created_at?: string
          id?: string
          tool_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "application_tools_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      applications: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          logo_url: string | null
          name: string
          status: string | null
          type: string | null
          updated_at: string | null
          url: string | null
          version: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          logo_url?: string | null
          name: string
          status?: string | null
          type?: string | null
          updated_at?: string | null
          url?: string | null
          version?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          logo_url?: string | null
          name?: string
          status?: string | null
          type?: string | null
          updated_at?: string | null
          url?: string | null
          version?: string | null
        }
        Relationships: []
      }
      apps: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          name: string
          platform_id: string
          status: Database["public"]["Enums"]["app_status"] | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          name: string
          platform_id: string
          status?: Database["public"]["Enums"]["app_status"] | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          platform_id?: string
          status?: Database["public"]["Enums"]["app_status"] | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "apps_platform_id_fkey"
            columns: ["platform_id"]
            isOneToOne: false
            referencedRelation: "platforms"
            referencedColumns: ["id"]
          },
        ]
      }
      chat_sessions: {
        Row: {
          application_id: string
          chat_id: string
          created_at: string
          flow_id: string | null
          id: string
          is_pinned: boolean | null
          last_message_at: string | null
          last_message_content: string | null
          message_count: number | null
          organization_id: string | null
          source: string | null
          title: string
          updated_at: string
          user_id: string | null
        }
        Insert: {
          application_id: string
          chat_id: string
          created_at?: string
          flow_id?: string | null
          id?: string
          is_pinned?: boolean | null
          last_message_at?: string | null
          last_message_content?: string | null
          message_count?: number | null
          organization_id?: string | null
          source?: string | null
          title?: string
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          application_id?: string
          chat_id?: string
          created_at?: string
          flow_id?: string | null
          id?: string
          is_pinned?: boolean | null
          last_message_at?: string | null
          last_message_content?: string | null
          message_count?: number | null
          organization_id?: string | null
          source?: string | null
          title?: string
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "chat_sessions_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chat_sessions_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      checkpoints: {
        Row: {
          checkpoint: string | null
          checkpoint_id: string
          metadata: string | null
          parent_id: string | null
          thread_id: string
        }
        Insert: {
          checkpoint?: string | null
          checkpoint_id: string
          metadata?: string | null
          parent_id?: string | null
          thread_id: string
        }
        Update: {
          checkpoint?: string | null
          checkpoint_id?: string
          metadata?: string | null
          parent_id?: string | null
          thread_id?: string
        }
        Relationships: []
      }
      files: {
        Row: {
          access_level: string | null
          bucket: string | null
          content_type: string | null
          context_id: string | null
          context_type: string | null
          created_at: string
          created_by: string | null
          description: string | null
          id: string
          is_deleted: boolean
          is_public: boolean | null
          is_shareable: boolean
          metadata: Json | null
          name: string | null
          path: string | null
          path_tokens: string[] | null
          resource_id: string | null
          resource_type: string | null
          size: number | null
          updated_at: string | null
          url: string | null
        }
        Insert: {
          access_level?: string | null
          bucket?: string | null
          content_type?: string | null
          context_id?: string | null
          context_type?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          is_deleted?: boolean
          is_public?: boolean | null
          is_shareable?: boolean
          metadata?: Json | null
          name?: string | null
          path?: string | null
          path_tokens?: string[] | null
          resource_id?: string | null
          resource_type?: string | null
          size?: number | null
          updated_at?: string | null
          url?: string | null
        }
        Update: {
          access_level?: string | null
          bucket?: string | null
          content_type?: string | null
          context_id?: string | null
          context_type?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          is_deleted?: boolean
          is_public?: boolean | null
          is_shareable?: boolean
          metadata?: Json | null
          name?: string | null
          path?: string | null
          path_tokens?: string[] | null
          resource_id?: string | null
          resource_type?: string | null
          size?: number | null
          updated_at?: string | null
          url?: string | null
        }
        Relationships: []
      }
      flow_runs: {
        Row: {
          application_id: string
          chat_id: string | null
          created_at: string
          duration_ms: number | null
          error: string | null
          flow_id: string
          id: string
          input_text: string | null
          model_name: string | null
          organization_id: string | null
          output_text: string | null
          source: string | null
          status: string
          tokens_used: number | null
          updated_at: string
          user_id: string | null
        }
        Insert: {
          application_id: string
          chat_id?: string | null
          created_at?: string
          duration_ms?: number | null
          error?: string | null
          flow_id: string
          id?: string
          input_text?: string | null
          model_name?: string | null
          organization_id?: string | null
          output_text?: string | null
          source?: string | null
          status?: string
          tokens_used?: number | null
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          application_id?: string
          chat_id?: string | null
          created_at?: string
          duration_ms?: number | null
          error?: string | null
          flow_id?: string
          id?: string
          input_text?: string | null
          model_name?: string | null
          organization_id?: string | null
          output_text?: string | null
          source?: string | null
          status?: string
          tokens_used?: number | null
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "flow_runs_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "flow_runs_chat_id_fkey"
            columns: ["chat_id"]
            isOneToOne: false
            referencedRelation: "chat_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "flow_runs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      hook_debug_logs: {
        Row: {
          created_at: string | null
          debug_info: Json
          hook_name: string
          id: number
        }
        Insert: {
          created_at?: string | null
          debug_info: Json
          hook_name: string
          id?: number
        }
        Update: {
          created_at?: string | null
          debug_info?: Json
          hook_name?: string
          id?: number
        }
        Relationships: []
      }
      organization_users: {
        Row: {
          created_at: string
          id: string
          organization_id: string
          role: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          organization_id: string
          role?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          organization_id?: string
          role?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "organization_users_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          application_id: string | null
          created_at: string | null
          description: string | null
          id: string
          name: string
          updated_at: string | null
        }
        Insert: {
          application_id?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          name: string
          updated_at?: string | null
        }
        Update: {
          application_id?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "organizations_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      permission_categories: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      permissions: {
        Row: {
          category_id: string
          context_types: string[]
          created_at: string
          description: string | null
          id: string
          name: string
        }
        Insert: {
          category_id: string
          context_types: string[]
          created_at?: string
          description?: string | null
          id?: string
          name: string
        }
        Update: {
          category_id?: string
          context_types?: string[]
          created_at?: string
          description?: string | null
          id?: string
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "permissions_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "permission_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      platform_enabled_nodes: {
        Row: {
          created_at: string | null
          enabled: boolean | null
          id: string
          node_type: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          enabled?: boolean | null
          id?: string
          node_type: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          enabled?: boolean | null
          id?: string
          node_type?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      platform_enabled_tools: {
        Row: {
          created_at: string | null
          enabled: boolean | null
          id: string
          tool_type: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          enabled?: boolean | null
          id?: string
          tool_type: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          enabled?: boolean | null
          id?: string
          tool_type?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      platform_settings: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          is_encrypted: boolean | null
          key: string
          updated_at: string | null
          value: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          is_encrypted?: boolean | null
          key: string
          updated_at?: string | null
          value?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          is_encrypted?: boolean | null
          key?: string
          updated_at?: string | null
          value?: string | null
        }
        Relationships: []
      }
      platforms: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          name: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          name: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      role_permissions: {
        Row: {
          created_at: string
          id: string
          permission: string
          role_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          permission: string
          role_id: string
        }
        Update: {
          created_at?: string
          id?: string
          permission?: string
          role_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "role_permissions_role_id_fkey"
            columns: ["role_id"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["id"]
          },
        ]
      }
      roles: {
        Row: {
          base_role: string | null
          context_id: string | null
          context_type: string
          created_at: string
          created_by: string
          description: string | null
          id: string
          name: string
          role_type: string | null
          updated_at: string
        }
        Insert: {
          base_role?: string | null
          context_id?: string | null
          context_type: string
          created_at?: string
          created_by: string
          description?: string | null
          id?: string
          name: string
          role_type?: string | null
          updated_at?: string
        }
        Update: {
          base_role?: string | null
          context_id?: string | null
          context_type?: string
          created_at?: string
          created_by?: string
          description?: string | null
          id?: string
          name?: string
          role_type?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      sam_emails: {
        Row: {
          attachments: string | null
          "body-html": string | null
          "body-plain": string | null
          "content-type": string | null
          created_at: string | null
          date: string | null
          domain: string | null
          from: string | null
          goal: string | null
          id: number | null
          "message-headers": string | null
          "message-id": string
          "message-url": string | null
          modified_at: string | null
          "parent-session-id": string | null
          received: string | null
          recipient: string | null
          "return-path": string | null
          "sam-status": string | null
          sender: string | null
          "session-id": string | null
          signature: string | null
          "stripped-html": string | null
          "stripped-text": string | null
          subject: string | null
          timestamp: string | null
          to: string | null
          token: string | null
          uuid: string
          "x-entity-ref-id": string | null
          "x-envelope-from": string[] | null
          "x-mailer": string | null
          "x-mailgun-incoming": string | null
          "x-received": string | null
        }
        Insert: {
          attachments?: string | null
          "body-html"?: string | null
          "body-plain"?: string | null
          "content-type"?: string | null
          created_at?: string | null
          date?: string | null
          domain?: string | null
          from?: string | null
          goal?: string | null
          id?: number | null
          "message-headers"?: string | null
          "message-id": string
          "message-url"?: string | null
          modified_at?: string | null
          "parent-session-id"?: string | null
          received?: string | null
          recipient?: string | null
          "return-path"?: string | null
          "sam-status"?: string | null
          sender?: string | null
          "session-id"?: string | null
          signature?: string | null
          "stripped-html"?: string | null
          "stripped-text"?: string | null
          subject?: string | null
          timestamp?: string | null
          to?: string | null
          token?: string | null
          uuid?: string
          "x-entity-ref-id"?: string | null
          "x-envelope-from"?: string[] | null
          "x-mailer"?: string | null
          "x-mailgun-incoming"?: string | null
          "x-received"?: string | null
        }
        Update: {
          attachments?: string | null
          "body-html"?: string | null
          "body-plain"?: string | null
          "content-type"?: string | null
          created_at?: string | null
          date?: string | null
          domain?: string | null
          from?: string | null
          goal?: string | null
          id?: number | null
          "message-headers"?: string | null
          "message-id"?: string
          "message-url"?: string | null
          modified_at?: string | null
          "parent-session-id"?: string | null
          received?: string | null
          recipient?: string | null
          "return-path"?: string | null
          "sam-status"?: string | null
          sender?: string | null
          "session-id"?: string | null
          signature?: string | null
          "stripped-html"?: string | null
          "stripped-text"?: string | null
          subject?: string | null
          timestamp?: string | null
          to?: string | null
          token?: string | null
          uuid?: string
          "x-entity-ref-id"?: string | null
          "x-envelope-from"?: string[] | null
          "x-mailer"?: string | null
          "x-mailgun-incoming"?: string | null
          "x-received"?: string | null
        }
        Relationships: []
      }
      secrets: {
        Row: {
          created_at: string | null
          id: string
          key_id: string | null
          metadata: Json | null
          name: string
          type: string
          updated_at: string | null
          value: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          key_id?: string | null
          metadata?: Json | null
          name: string
          type: string
          updated_at?: string | null
          value: string
        }
        Update: {
          created_at?: string | null
          id?: string
          key_id?: string | null
          metadata?: Json | null
          name?: string
          type?: string
          updated_at?: string | null
          value?: string
        }
        Relationships: []
      }
      slack_sessions: {
        Row: {
          created_at: string
          first_name: string | null
          id: number
          last_name: string | null
          remodl_org_id: string | null
          remodl_user_id: string | null
          slack_team: string | null
          slack_user_id: string | null
          tz: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string
          first_name?: string | null
          id?: number
          last_name?: string | null
          remodl_org_id?: string | null
          remodl_user_id?: string | null
          slack_team?: string | null
          slack_user_id?: string | null
          tz?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string
          first_name?: string | null
          id?: number
          last_name?: string | null
          remodl_org_id?: string | null
          remodl_user_id?: string | null
          slack_team?: string | null
          slack_user_id?: string | null
          tz?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      task_inbox: {
        Row: {
          channel: string | null
          created_at: string
          id: number
          remodl_user_id: string | null
          sessionId: string | null
          status: string | null
        }
        Insert: {
          channel?: string | null
          created_at?: string
          id?: number
          remodl_user_id?: string | null
          sessionId?: string | null
          status?: string | null
        }
        Update: {
          channel?: string | null
          created_at?: string
          id?: number
          remodl_user_id?: string | null
          sessionId?: string | null
          status?: string | null
        }
        Relationships: []
      }
      user_profiles: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          email: string | null
          first_name: string | null
          id: string
          last_name: string | null
          meta: Json | null
          phone: string | null
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          email?: string | null
          first_name?: string | null
          id?: string
          last_name?: string | null
          meta?: Json | null
          phone?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          email?: string | null
          first_name?: string | null
          id?: string
          last_name?: string | null
          meta?: Json | null
          phone?: string | null
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          created_at: string
          created_by: string
          id: string
          resource_id: string | null
          resource_type: string | null
          role_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          created_by: string
          id?: string
          resource_id?: string | null
          resource_type?: string | null
          role_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          created_by?: string
          id?: string
          resource_id?: string | null
          resource_type?: string | null
          role_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_custom_roles_role_id_fkey"
            columns: ["role_id"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      user_custom_roles_view: {
        Row: {
          created_at: string | null
          id: string | null
          resource_id: string | null
          resource_type: string | null
          role: string | null
          user_id: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      assign_custom_role: {
        Args: {
          p_user_id: string
          p_role_id: string
        }
        Returns: string
      }
      authorize: {
        Args: {
          requested_permission: string
        }
        Returns: boolean
      }
      authorize_resource: {
        Args: {
          requested_permission: string
          resource_type: string
          resource_id: string
        }
        Returns: boolean
      }
      authorize_secret_access: {
        Args: {
          secret_id: string
        }
        Returns: boolean
      }
      begin_transaction: {
        Args: Record<PropertyKey, never>
        Returns: undefined
      }
      commit_transaction: {
        Args: Record<PropertyKey, never>
        Returns: undefined
      }
      create_custom_role: {
        Args: {
          p_name: string
          p_description: string
          p_base_role: string
          p_context_type: string
          p_context_id: string
          p_permissions: string[]
        }
        Returns: string
      }
      custom_access_token_hook: {
        Args: {
          event: Json
        }
        Returns: Json
      }
      generate_api_key: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      get_all_applications_direct: {
        Args: Record<PropertyKey, never>
        Returns: {
          created_at: string | null
          description: string | null
          id: string
          logo_url: string | null
          name: string
          status: string | null
          type: string | null
          updated_at: string | null
          url: string | null
          version: string | null
        }[]
      }
      get_enabled_nodes: {
        Args: Record<PropertyKey, never>
        Returns: {
          node_type: string
        }[]
      }
      get_enabled_tools: {
        Args: Record<PropertyKey, never>
        Returns: {
          tool_type: string
        }[]
      }
      get_role_permissions_direct: {
        Args: {
          input_role_id: string
        }
        Returns: {
          permission: string
        }[]
      }
      hash_api_key: {
        Args: {
          api_key: string
        }
        Returns: string
      }
      is_platform_admin: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
      minimal_hook: {
        Args: {
          event: Json
        }
        Returns: Json
      }
      name_hook: {
        Args: {
          event: Json
        }
        Returns: Json
      }
      restore_deleted_file: {
        Args: {
          file_id: string
        }
        Returns: boolean
      }
      rollback_transaction: {
        Args: Record<PropertyKey, never>
        Returns: undefined
      }
      soft_delete_file: {
        Args: {
          file_id: string
        }
        Returns: boolean
      }
      toggle_node_enabled: {
        Args: {
          input_node_type: string
          input_enabled: boolean
        }
        Returns: boolean
      }
      toggle_tool_enabled: {
        Args: {
          input_tool_type: string
          input_enabled: boolean
        }
        Returns: boolean
      }
      user_belongs_to_organization: {
        Args: {
          org_id: string
        }
        Returns: boolean
      }
      user_has_application_access: {
        Args: {
          app_id: string
        }
        Returns: boolean
      }
      user_has_file_access: {
        Args: {
          file_id: string
        }
        Returns: boolean
      }
    }
    Enums: {
      app_status: "created" | "development" | "staging" | "production"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (PublicSchema["Tables"] & PublicSchema["Views"])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
        Database[PublicTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
      Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (PublicSchema["Tables"] &
        PublicSchema["Views"])
    ? (PublicSchema["Tables"] &
        PublicSchema["Views"])[PublicTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
    ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
    ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof PublicSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : PublicEnumNameOrOptions extends keyof PublicSchema["Enums"]
    ? PublicSchema["Enums"][PublicEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof PublicSchema["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof PublicSchema["CompositeTypes"]
    ? PublicSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never
