openapi: 3.1.0
info:
  title: API Key Schemas
  version: '1.0'
components:
  schemas:
    ApiKey:
      type: object
      description: Represents an API Key object as returned by the API.
      properties:
        id:
          type: string
          description: Unique identifier for the API key (string of length 20, not a UUID).
          maxLength: 20
        keyName:
          type: string
          description: A user-defined name for the API key.
        apiKey:
          type: string
          description: "The actual API key value. Returned by the API. Handle with care."
        apiSecret: 
          type: string
          description: "The stored salted and hashed version of the API key. SECURITY NOTE: This field is returned by the API but should ideally not be exposed or used client-side beyond initial setup if absolutely necessary."
        updatedDate:
          type: string
          format: date-time
          description: The date and time the API key was last updated.
      required:
        - id
        - keyName
        - apiKey
        - apiSecret 
        - updatedDate

    ApiKeyWithCount:
      type: object
      description: Represents an API Key object with an added chatflowCount field, omitting sensitive data like encryptedData.
      properties:
        id:
          type: string
          description: Unique identifier for the API key (string of length 20, not a UUID).
          maxLength: 20
        keyName:
          type: string
          description: A user-defined name for the API key.
        apiKey:
          type: string
          description: "The actual API key value. Returned by the API. Handle with care."
        chatflowCount:
          type: integer
          description: Number of chatflows associated with this API key.
        chatFlows:
          type: array
          description: Array of chatflows associated with this API key.
          items:
            type: object
            properties:
              flowName:
                type: string
                description: Name of the associated chatflow.
              category:
                type: string
                description: Category of the associated chatflow.
                nullable: true
              updatedDate:
                type: string
                format: date-time
                description: The date and time the chatflow was last updated.
        updatedDate:
          type: string
          format: date-time
          description: The date and time the API key was last updated.
      required:
        - id
        - keyName
        - apiKey
        - chatflowCount
        - chatFlows
        - updatedDate

    ApiKeyRequestBody:
      type: object
      description: Request body for creating or updating an API Key.
      required:
        - keyName
      properties:
        keyName:
          type: string
          description: User-defined name for the API key.
          example: "My Application Key"

    ApiKeyImportRequest:
      type: object
      description: Request body for importing API keys from a JSON file.
      required:
        - jsonFile
      properties:
        jsonFile:
          type: string
          format: data-uri
          description: "Data URI of the JSON file (e.g., data:application/json;base64,BASE64_ENCODED_JSON_ARRAY_OF_APIKEYS)"
        importMode:
          type: string
          enum: [replaceAll, errorIfExist, overwriteIfExist, ignoreIfExist]
          description: "Strategy for handling existing keys."
          nullable: true 