# Filename: api_documentation/schemas/modules/AssistantSchemas.yaml
openapi: 3.1.0
info:
  title: Assistant Schemas
  version: '1.0'
components:
  schemas:
    Assistant:
      type: object
      description: "Represents a Remodl Core Assistant entity."
      properties:
        id:
          type: string
          format: uuid
          description: "Unique identifier for the Remodl Core Assistant."
        details:
          type: string
          description: "JSON string containing the assistant's configuration. For OpenAI assistants, this is a serialized OpenAI Assistant object with additional metadata."
        credential:
          type: string
          format: uuid
          description: "Reference to the credential ID used by this assistant (e.g., OpenAI API key)."
        iconSrc:
          type: string
          nullable: true
          description: "Optional URL for the assistant's icon."
        type:
          type: string
          enum: ["CUSTOM", "OPENAI", "AZURE"]
          nullable: true
          description: "Type of assistant. Can be CUSTOM for local assistants, or OPENAI/AZURE for external API-backed assistants."
        createdDate:
          type: string
          format: date-time
          description: "Timestamp when the assistant was created."
        updatedDate:
          type: string
          format: date-time
          description: "Timestamp when the assistant was last updated."
      required:
        - id
        - details
        - credential
        - createdDate
        - updatedDate

    AssistantCreateRequest:
      type: object
      description: "Request body for creating a new Remodl Core Assistant."
      required:
        - details
      properties:
        details:
          type: string
          description: "JSON string of assistant configuration. For OpenAI assistants, this mirrors the OpenAI Assistant object structure with fields like name, model, instructions, tools, etc."
          example: '{"name":"My New Assistant","model":"gpt-4-turbo","instructions":"Be helpful."}'
        credential:
          type: string
          format: uuid
          description: "Credential ID (e.g., for OpenAI API key). Required if type is not CUSTOM."
        iconSrc:
          type: string
          nullable: true
          description: "Optional URL for the assistant's icon."
        type:
          type: string
          enum: ["CUSTOM", "OPENAI", "AZURE"]
          nullable: true
          description: "Type of assistant. Can be CUSTOM for local assistants, or OPENAI/AZURE for external API-backed assistants."