openapi: 3.1.0
info:
  title: Chatflows Schemas
  version: '1.0'
components:
  schemas:
    ChatflowTypeEnum:
      type: string
      enum: [CHATFLOW, MULTIAGENT, ASSISTANT, AGENTFLOW]
      description: The type of the chatflow.

    Chatflow:
      type: object
      description: Represents a Chatflow configuration.
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the chatflow.
          readOnly: true
        name:
          type: string
          description: Name of the chatflow.
        flowData:
          type: string # stringified JSON object
          description: "Stringified JSON object representing the chatflow's nodes and edges (e.g., IReactFlowObject structure)."
        deployed:
          type: boolean
          nullable: true
          description: Indicates if the chatflow is currently deployed.
        isPublic:
          type: boolean
          nullable: true
          description: Indicates if the chatflow is publicly accessible.
        apikeyid:
          type: string
          # format: uuid # The column is varchar, not explicitly uuid in migration for chat_flow.apikeyid
          nullable: true
          description: Optional API key ID linked to this chatflow for specific access control.
        chatbotConfig:
          type: string # stringified JSON object
          nullable: true
          description: "Stringified JSON object containing UI and behavioral configurations for the chatbot."
        apiConfig:
          type: string # stringified JSON object
          nullable: true
          description: "Stringified JSON object for API-specific configurations for the chatflow."
        analytic:
          type: string # stringified JSON object
          nullable: true
          description: "Stringified JSON object for analytics configurations."
        speechToText:
          type: string # stringified JSON object
          nullable: true
          description: "Stringified JSON object for speech-to-text service configurations."
        followUpPrompts:
          type: string # stringified JSON object
          nullable: true
          description: "Stringified JSON array for follow-up prompt suggestions."
        category:
          type: string
          nullable: true
          description: Category of the chatflow, for organization.
        type:
          $ref: '#/components/schemas/ChatflowTypeEnum'
          nullable: true
        createdDate:
          type: string
          format: date-time
          description: Timestamp of when the chatflow was created.
          readOnly: true
        updatedDate:
          type: string
          format: date-time
          description: Timestamp of when the chatflow was last updated.
          readOnly: true
      required:
        - id
        - name
        - flowData
        - createdDate
        - updatedDate

    ChatflowRequestBody:
      type: object
      description: Request body for creating or updating a chatflow.
      properties:
        name:
          type: string
          description: Name of the chatflow.
        flowData:
          type: string # stringified JSON object
          description: "Stringified JSON object representing the chatflow's nodes and edges."
        deployed:
          type: boolean
          nullable: true
        isPublic:
          type: boolean
          nullable: true
        apikeyid:
          type: string
          nullable: true
        chatbotConfig:
          type: string # stringified JSON object
          nullable: true
        apiConfig:
          type: string # stringified JSON object
          nullable: true
        analytic:
          type: string # stringified JSON object
          nullable: true
        speechToText:
          type: string # stringified JSON object
          nullable: true
        followUpPrompts:
          type: string # stringified JSON object
          nullable: true
        category:
          type: string
          nullable: true
        type:
          $ref: '#/components/schemas/ChatflowTypeEnum'
          nullable: true
      required: # Minimum required for a meaningful create/update
        - name
        - flowData

    ChatflowResponse:
      type: object
      description: Response returned when retrieving a chatflow.
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the chatflow.
        name:
          type: string
          description: Name of the chatflow.
        flowData:
          type: string
          description: "Stringified JSON object representing the chatflow's nodes and edges."
        deployed:
          type: boolean
          nullable: true
          description: Indicates if the chatflow is currently deployed.
        isPublic:
          type: boolean
          description: Indicates that the chatflow is publicly accessible (will be true for responses from public endpoints).
        apikeyid:
          type: string
          nullable: true
          description: Optional API key ID linked to this chatflow.
        chatbotConfig:
          type: string
          nullable: true
          description: "Stringified JSON object containing UI and behavioral configurations for the chatbot."
        apiConfig:
          type: string
          nullable: true
          description: "Stringified JSON object for API-specific configurations."
        analytic:
          type: string
          nullable: true
          description: "Stringified JSON object for analytics configurations."
        speechToText:
          type: string
          nullable: true
          description: "Stringified JSON object for speech-to-text service configurations."
        followUpPrompts:
          type: string
          nullable: true
          description: "Stringified JSON array for follow-up prompt suggestions."
        category:
          type: string
          nullable: true
          description: Category of the chatflow.
        type:
          $ref: '#/components/schemas/ChatflowTypeEnum'
          nullable: true
          description: The type of the chatflow.
        createdDate:
          type: string
          format: date-time
          description: Timestamp of when the chatflow was created.
        updatedDate:
          type: string
          format: date-time
          description: Timestamp of when the chatflow was last updated.

    GetAllChatflowsResponse:
      type: array
      items:
        $ref: '#/components/schemas/Chatflow'
