openapi: 3.1.0
info:
  title: Components Credentials Schemas
  version: '1.0'
components:
  schemas:
    ComponentCredentialInputParam: # Alias for INodeParamSchema for clarity in this context
      $ref: '../shared/flowiseComponentSchemas.yaml#/components/schemas/INodeParamSchema'

    ComponentCredentialDefinition:
      type: object
      description: "Defines a type of component credential and its required input parameters."
      properties:
        label:
          type: string
          description: "Display label for the credential type."
        name:
          type: string
          description: "Internal name/identifier for the credential type (e.g., openAIApi)."
        description:
          type: string
          nullable: true
          description: "Optional description of the credential type."
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/ComponentCredentialInputParam'
          nullable: true
          description: "Array of input parameters required to configure this credential type."
      required:
        - label
        - name

    GetAllComponentsCredentialsResponse:
      type: array
      items:
        $ref: '#/components/schemas/ComponentCredentialDefinition'
      description: "A list of all available component credential definitions."

    GetComponentCredentialByNameResponse:
      oneOf:
        - $ref: '#/components/schemas/ComponentCredentialDefinition'
        - type: array
          items:
            $ref: '#/components/schemas/ComponentCredentialDefinition'
      description: "A single component credential definition or an array if multiple names were queried using '&' in the name parameter." 