openapi: 3.1.0
info:
  title: Credentials Schemas
  version: '1.0'
components:
  schemas:
    PlainDataInputOutput: 
      type: object
      additionalProperties: true
      description: "Object containing the actual credential fields (e.g., apiKey, secretKey). Structure varies by credential type."
      example:
        apiKey: "your_api_key_here"
        anotherParam: "value"

    CredentialBase:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the credential instance.
          readOnly: true
        name:
          type: string
          description: User-defined name for this credential instance.
        credentialName:
          type: string
          description: "Type of the credential (e.g., openAIApi, awsS3Api)."
        createdDate:
          type: string
          format: date-time
          description: Timestamp of when the credential was created.
          readOnly: true
        updatedDate:
          type: string
          format: date-time
          description: Timestamp of when the credential was last updated.
          readOnly: true
      required:
        - id
        - name
        - credentialName
        - createdDate
        - updatedDate

    CredentialResponse: # Represents ICredentialReturnResponse
      type: object # Changed from allOf for direct property definition
      description: Represents a credential instance with its decrypted data.
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the credential instance.
          readOnly: true
        name:
          type: string
          description: User-defined name for this credential instance.
        credentialName:
          type: string
          description: "Type of the credential (e.g., openAIApi, awsS3Api)."
        createdDate:
          type: string
          format: date-time
          description: Timestamp of when the credential was created.
          readOnly: true
        updatedDate:
          type: string
          format: date-time
          description: Timestamp of when the credential was last updated.
          readOnly: true
        plainDataObj:
          $ref: '#/components/schemas/PlainDataInputOutput'
          description: "The decrypted credential data fields."
      required:
        - id
        - name
        - credentialName
        - createdDate
        - updatedDate
        - plainDataObj # plainDataObj is part of ICredentialReturnResponse

    CreateCredentialRequestBody: # Represents ICredentialReqBody
      type: object
      description: Request body for creating a new credential instance.
      properties:
        name:
          type: string
          description: User-defined name for this credential instance.
        credentialName:
          type: string
          description: "Type of the credential (e.g., openAIApi, awsS3Api)."
        plainDataObj:
          $ref: '#/components/schemas/PlainDataInputOutput'
          description: "Object containing the actual credential fields to be encrypted and stored."
      required:
        - name
        - credentialName
        - plainDataObj
        
    UpdateCredentialRequestBody:
      type: object
      description: Request body for updating a credential instance's name or type. Does not update encrypted data.
      properties:
        name:
          type: string
          description: New user-defined name for this credential instance.
        credentialName:
          type: string
          description: "New type of the credential (e.g., openAIApi, awsS3Api)."
      # Client should send at least one. API might enforce this.
      # For schema, making both individually optional by not listing in `required`.
      # Consider adding minProperties: 1 if stricter validation via schema is desired and supported.

    GetAllCredentialsResponse:
      type: array
      items:
        $ref: '#/components/schemas/CredentialResponse' 