openapi: 3.1.0
info:
  title: Executions Schemas
  version: '1.0'
components:
  schemas:
    ExecutionStateEnum:
      type: string
      enum: [INPROGRESS, FINISHED, ERROR, TERMINATED, TIMEOUT, STOPPED]
      description: The current state of an agent flow execution.

    ExecutionObject:
      type: object
      description: Represents an agent flow execution record.
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the execution.
          readOnly: true
        executionData:
          type: string # Stringified JSON
          description: "Detailed data of the execution, typically a JSON string representing steps, inputs, outputs, and state."
        state:
          $ref: '#/components/schemas/ExecutionStateEnum'
        agentflowId:
          type: string
          format: uuid
          description: "ID of the ChatFlow (Agentflow) this execution belongs to."
        sessionId:
          type: string
          format: uuid
          description: "Session ID for this execution."
        action:
          type: string # Potentially stringified JSON
          nullable: true
          description: "Last action taken or required in the execution, if applicable (may be stringified JSON)."
        isPublic:
          type: boolean
          nullable: true
          description: "Indicates if this execution record is publicly accessible (e.g., for shared results)."
        createdDate:
          type: string
          format: date-time
          description: Timestamp of when the execution record was created.
          readOnly: true
        updatedDate:
          type: string
          format: date-time
          description: Timestamp of when the execution record was last updated.
          readOnly: true
        stoppedDate:
          type: string
          format: date-time
          description: "Timestamp of when the execution stopped (finished, errored, terminated, etc.)."
      required:
        - id
        - executionData
        - state
        - agentflowId
        - sessionId
        - createdDate
        - updatedDate
        - stoppedDate

    ExecutionResponse:
      type: object
      description: "Processed execution object with parsed executionData and action fields."
      allOf:
        - $ref: '#/components/schemas/ExecutionObject'
      example:
        id: "123e4567-e89b-12d3-a456-426614174000"
        executionData: [{"nodeId": "1", "nodeLabel": "Start", "data": {"output": "Hello"}}]
        state: "FINISHED"
        agentflowId: "98765432-e89b-12d3-a456-426614174000"
        sessionId: "abcdef12-e89b-12d3-a456-426614174000"
        createdDate: "2023-01-01T12:00:00Z"
        updatedDate: "2023-01-01T12:15:00Z"
        stoppedDate: "2023-01-01T12:15:00Z"

    DeleteResult:
      type: object
      description: "Result of a delete operation from TypeORM or a similar format."
      properties:
        success:
          type: boolean
          description: "Whether the delete operation was successful."
        deletedCount:
          type: integer
          description: "Number of records that were deleted."
      required:
        - success
        - deletedCount

    PaginatedExecutionsResponse:
      type: object
      description: "Paginated response for executions."
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ExecutionObject'
          description: "Array of execution records for the current page."
        total:
          type: integer
          description: "Total number of execution records matching the query."
      required:
        - data
        - total

    UpdateExecutionRequestBody:
      type: object
      description: "Request body for updating an execution. Allows partial updates to mutable fields."
      properties:
        executionData:
          type: string
          description: "Updated detailed data of the execution (stringified JSON)."
          nullable: true 
        state:
          $ref: '#/components/schemas/ExecutionStateEnum'
          nullable: true
        action:
          type: string
          description: "Updated action information (potentially stringified JSON)."
          nullable: true
        isPublic:
          type: boolean
          nullable: true
        stoppedDate:
          type: string
          format: date-time
          nullable: true

    DeleteExecutionsRequestBody:
      type: object
      description: "Request body for deleting multiple executions by their IDs."
      properties:
        executionIds:
          type: array
          items:
            type: string
            format: uuid
          description: "An array of execution IDs to be deleted."
          minItems: 1
      required:
        - executionIds