openapi: 3.1.0
info:
  title: Flow Config Schemas
  version: '1.0'
components:
  schemas:
    FlowConfigResponse:
      type: object
      properties:
        chatbotConfig:
          type: object
          additionalProperties: true
          description: "Parsed chatbotConfig from ChatFlow entity or empty object."
        speechToText:
          type: object
          additionalProperties: true
          description: "Parsed speechToText configuration from ChatFlow entity or empty object."
        uploadsConfig:
          $ref: "#/components/schemas/UploadConfig"
    
    UploadConfig:
      type: object
      properties:
        acceptedMimeTypes:
          type: array
          items:
            type: string
          description: "Array of MIME types accepted for uploads."
        maxUploads:
          type: integer
          description: "Maximum number of files that can be uploaded."
        maxFileSize:
          type: integer
          description: "Maximum file size in bytes." 