openapi: 3.1.0
info:
  title: Leads Schemas
  version: '1.0'
components:
  schemas:
    LeadObject:
      type: object
      description: Represents a captured lead.
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the lead record.
          readOnly: true
        name:
          type: string
          nullable: true
          description: Name of the lead.
        email:
          type: string
          format: email
          nullable: true
          description: Email address of the lead.
        phone:
          type: string
          nullable: true
          description: Phone number of the lead.
        chatflowid:
          type: string
          description: ID of the chatflow where the lead was captured.
        chatId:
          type: string
          description: ID of the specific chat session that generated the lead.
        createdDate:
          type: string
          format: date-time
          description: Timestamp of when the lead was created.
          readOnly: true
      required:
        - id
        - chatflowid
        - chatId
        - createdDate

    CreateLeadRequestBody:
      type: object
      description: Request body for creating a new lead.
      properties:
        name:
          type: string
          nullable: true
          description: Name of the lead.
        email:
          type: string
          format: email
          nullable: true
          description: Email address of the lead.
        phone:
          type: string
          nullable: true
          description: Phone number of the lead.
        chatflowid:
          type: string
          description: ID of the chatflow this lead is associated with.
        chatId:
          type: string
          nullable: true # Service generates if not provided
          description: ID of the specific chat session. If not provided, a new one might be generated.
      required:
        - chatflowid # Essential for context
        # name, email, or phone would typically be required for a useful lead, but API takes Partial<ILead>.
        # Minimal requirement is chatflowid as per how service uses it to link.

    GetAllLeadsResponse:
      type: array
      items:
        $ref: '#/components/schemas/LeadObject'
      description: A list of leads for a given chatflow. 