openapi: 3.1.0
info:
  title: Leads Schemas
  version: '1.0'
components:
  schemas:
    LeadObject:
      type: object
      description: "Represents a captured lead from a chatflow interaction."
      properties:
        id:
          type: string
          format: uuid
          description: "Unique identifier of the lead record."
          readOnly: true
        name:
          type: string
          nullable: true
          description: "Name of the lead."
        email:
          type: string
          format: email
          nullable: true
          description: "Email address of the lead."
        phone:
          type: string
          nullable: true
          description: "Phone number of the lead."
        chatflowid:
          type: string
          description: "ID of the chatflow where the lead was captured."
        chatId:
          type: string
          description: "ID of the specific chat session that generated the lead."
        createdDate:
          type: string
          format: date-time
          description: "Timestamp of when the lead was created."
          readOnly: true
      required:
        - id
        - chatflowid
        - chatId
        - createdDate

    CreateLeadRequestBody:
      type: object
      description: "Request body for creating a new lead. Only chatflowid is required, though a practical lead submission would typically include at least one contact field."
      properties:
        name:
          type: string
          nullable: true
          description: "Name of the lead."
        email:
          type: string
          format: email
          nullable: true
          description: "Email address of the lead."
        phone:
          type: string
          nullable: true
          description: "Phone number of the lead."
        chatflowid:
          type: string
          description: "ID of the chatflow this lead is associated with."
        chatId:
          type: string
          nullable: true 
          description: "ID of the specific chat session. If not provided, a new UUID will be generated by the server."
      required:
        - chatflowid

    GetAllLeadsResponse:
      type: array
      items:
        $ref: '#/components/schemas/LeadObject'
      description: "A list of leads for a given chatflow." 