openapi: 3.1.0
info:
  title: NVIDIA NIM Schemas
  version: '1.0'
components:
  schemas:
    NimModel:
      type: object
      description: "Represents a NVIDIA NIM model."
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: "The identifier for the model used in API calls."
          example: "playground_llama2_13b"
        name:
          type: string
          description: "Display name of the model."
          example: "Llama2-13B"
        label:
          type: string
          description: "Label for UI display, typically same as name."
          example: "Llama2-13B"
        modelType:
          type: string
          description: "Type of the model, if provided by NVIDIA API."
        state:
          type: string
          description: "State of the model, if provided by NVIDIA API."
          enum: ["ACTIVE", "INACTIVE", "MAINTENANCE"]
    
    NimAuthTokenResponse:
      type: object
      description: "Response from the NVIDIA token service."
      required:
        - token
        - expiry
      properties:
        token:
          type: string
          description: "Authentication token for NVIDIA NIM API."
        expiry:
          type: string
          format: date-time
          description: "Expiration time of the token."
    
    NimContainer:
      type: object
      description: "Information about a running NVIDIA NIM container."
      properties:
        id:
          type: string
          description: "Container ID."
        image:
          type: string
          description: "Image name used for the container."
        name:
          type: string
          description: "Container name."
        port:
          type: string
          description: "Port exposed by the container."
        status:
          type: string
          description: "Container status."
        created:
          type: string
          description: "Creation timestamp."
    
    NimImage:
      type: object
      description: "Information about a NVIDIA NIM image."
      properties:
        id:
          type: string
          description: "Image ID."
        name:
          type: string
          description: "Image name."
        tag:
          type: string
          description: "Image tag."
        size:
          type: string
          description: "Image size."
        created:
          type: string
          description: "Creation timestamp."
    
    NimContainerStartRequest:
      type: object
      description: "Request to start a NVIDIA NIM container."
      required:
        - imageTag
        - hostPort
      properties:
        imageTag:
          type: string
          description: "Tag of the image to run."
          example: "llama2:13b"
        apiKey:
          type: string
          description: "NVIDIA API key for authentication."
        hostPort:
          type: string
          description: "Port to expose on the host."
          example: "8080"
        nimRelaxMemConstraints:
          type: integer
          description: "Whether to relax memory constraints (0 = false, 1 = true)."
          enum: [0, 1]
          default: 0 