# Filename: api_documentation/schemas/modules/openAiAssistantSchemas.yaml
openapi: 3.1.0
info:
  title: OpenAI Assistant Schemas
  version: '1.0'
components:
  schemas:
    OpenAIAssistant:
      type: object
      description: "Represents an OpenAI Assistant object."
      properties:
        id:
          type: string
          description: "The identifier, which can be referenced in API endpoints."
        object:
          type: string
          enum: [assistant]
          description: "The object type, which is always `assistant`."
        created_at:
          type: integer
          format: unixtime
          description: "The Unix timestamp (in seconds) for when the assistant was created."
        name:
          type: string
          nullable: true
          description: "The name of the assistant."
        description:
          type: string
          nullable: true
          description: "The description of the assistant."
        model:
          type: string
          description: "ID of the model to use. You can use the [List models](https://platform.openai.com/docs/api-reference/models/list) API to see all of your available models."
        instructions:
          type: string
          nullable: true
          description: "The system instructions that the assistant uses."
        tools:
          type: array
          items:
            type: object # Can be one of CodeInterpreter, FileSearch, FunctionTool
            oneOf: 
              - $ref: '#/components/schemas/OpenAICodeInterpreterTool'
              - $ref: '#/components/schemas/OpenAIFileSearchTool' 
              - $ref: '#/components/schemas/OpenAIFunctionTool'
          description: "A list of tools enabled for the assistant."
        tool_resources: 
          type: object
          nullable: true
          properties:
            code_interpreter:
              type: object
              properties:
                file_ids:
                  type: array
                  items:
                    type: string
                  description: "A list of file IDs attached to this assistant for Code Interpreter."
              nullable: true
            file_search: 
              type: object
              properties:
                vector_store_ids:
                  type: array
                  items:
                    type: string
                  description: "A list of vector store IDs attached to this assistant for File Search."
              nullable: true
          description: "A set of resources that are used by the assistant's tools."
        metadata:
          type: object
          additionalProperties: true
          nullable: true
          description: "Set of 16 key-value pairs that can be attached to an object."
        temperature:
          type: number
          format: float
          nullable: true
          default: 1
        top_p:
          type: number
          format: float
          nullable: true
          default: 1
        response_format:
          oneOf:
            - type: string
              enum: [auto]
            - type: object
              properties:
                type:
                  type: string
                  enum: [json_object, text]
              required: [type]
          nullable: true
          description: "Specifies the format that the model must output."
      required:
        - id
        - object
        - created_at
        - model
        - tools

    OpenAICodeInterpreterTool:
      type: object
      properties:
        type:
          type: string
          enum: [code_interpreter]
      required: [type]

    OpenAIFileSearchTool: 
      type: object
      properties:
        type:
          type: string
          enum: [file_search]
      required: [type]

    OpenAIFunctionTool:
      type: object
      properties:
        type:
          type: string
          enum: [function]
        function:
          type: object 
          properties:
            name: { type: string, description: "The name of the function to be called." }
            description: { type: string, nullable: true, description: "A description of what the function does, used by the model to choose when and how to call the function." }
            parameters: 
              type: object
              additionalProperties: true
              description: "The parameters the functions accepts, described as a JSON Schema object."
          required: [name, parameters]
      required: [type, function]

    OpenAIFileObject:
      type: object
      description: "Represents a file uploaded to OpenAI."
      properties:
        id:
          type: string
          description: "The file identifier, which can be referenced in API endpoints."
        object:
          type: string
          enum: [file]
          description: "The object type, which is always `file`."
        bytes:
          type: integer
          description: "The size of the file, in bytes."
        created_at:
          type: integer
          format: unixtime
          description: "The Unix timestamp (in seconds) for when the file was created."
        filename:
          type: string
          description: "The name of the file."
        purpose:
          type: string
          enum: [fine-tune, fine-tune-results, assistants, assistants_output, vision]
          description: "The intended purpose of the file."
        status: 
          type: string
          enum: [uploaded, processed, error]
          description: "The current status of the file."
          nullable: true 
        status_details:
          type: string
          nullable: true
          description: "Additional details about the status of the file if it is in an error state."
      required:
        - id
        - object
        - bytes
        - created_at
        - filename
        - purpose

    # ... (Next: OpenAIThread, OpenAIMessage, OpenAIRun, OpenAIRunStep, etc. schemas) ...
