"/flow-config/{id}":
  get:
    summary: "INTERNAL: Get Specific Flow Configuration"
    operationId: "internalFlowConfigGetById"
    tags: ["Flow Config", "InternalAPI"]
    parameters:
      - name: id
        in: path
        required: true
        description: "ID of the Chatflow."
        schema: { type: string, format: uuid }
    responses:
      '200':
        description: "Successfully retrieved flow configurations."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FlowConfigResponse"
      '404':
        description: "Not Found - Chatflow with ID not found."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ErrorResponse"
      '412':
        description: "Precondition Failed - ID not provided."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ErrorResponse"
      '500':
        description: "Internal Server Error."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ErrorResponse"
