openapi: 3.1.0
info:
  title: Shared Common Schemas
  version: '1.0'
components:
  schemas:
    ChatMessage:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          enum: [userMessage, apiMessage, user, assistant, system, function, tool]
          description: The role of the message sender.
        content:
          type: string
          description: The textual content of the message.
        name: # For tool calls
          type: string
          description: The name of the tool that was called (if role is 'tool').
        tool_call_id: # For tool calls
          type: string
          description: The ID of the tool call (if role is 'tool').
        tool_calls: # For assistant messages requesting tool calls
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              type:
                type: string
                enum: [function]
              function:
                type: object
                properties:
                  name:
                    type: string
                  arguments:
                    type: string # JSON string

    ErrorResponse:
      type: object
      required:
        - statusCode
        - error
        - message
      properties:
        statusCode:
          type: integer
          format: int32
          description: HTTP status code.
        error:
          type: string
          description: Short error description (e.g., 'Not Found', 'Internal ServerError').
        message:
          type: string
          description: Detailed error message.
        requestId: # Optional
          type: string
          description: Optional request identifier for tracing.
